name: ${project.name}
main: studio.magemonkey.fabled.Fabled
version: ${project.version}
authors: [ Travja, goflish, Eniripsa96, Sentropic ]
depend: [ Codex ]
softdepend:
  - Vault
  - Citizens
  - LibsDisguises
  - PlaceholderAPI
  - NoCheatPlus
  - MythicMobs
  - WorldGuard
  - WorldEdit
  - Mimic
  - ProtocolLib
loadbefore: [ Divinity, Quests, TAB ]
provides: [ SkillAPI, ProSkillAPI ]
api-version: 1.16

permissions:
  fabled.basic:
    description: access to skill trees and using skills
    default: true
  fabled.reset:
    description: access to resetting your class
    default: true
  fabled.exp:
    description: access to gaining exp
    default: true
  fabled.level:
    description: access to using the level and exp commands
    default: op
  fabled.mana:
    description: access to using the mana command
    default: op
  fabled.points:
    description: access to using the points command
    default: op
  fabled.reload:
    description: access to using the reload command
    default: op
  fabled.class:
    description: access to all classes
    default: op
  fabled.skill:
    description: access to all skills
    default: op
  fabled.lore:
    description: access to all lore commands
    default: op
  fabled.force:
    description: access to force commands
    default: op
  fabled.attrib:
    description: access to giving attribute points
    default: op
  fabled.gui:
    description: access to GUI editor menu
    default: op

  fabled.*:
    description: access to all commands and features
    default: op
    children:
      fabled.basic: true
      fabled.reset: true
      fabled.exp: true
      fabled.level: true
      fabled.mana: true
      fabled.points: true
      fabled.reload: true
      fabled.class: true
      fabled.skill: true
      skillapi.lore: true
      skillapi.gui: true
