name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - Travja
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Have you tried to reproduce this without OP?
      description: Please remove OP from yourself and confirm that the bug still occurs without OP.
      options:
        - label: I have tested without OP
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Right click '....'
        4. Action doesn't happen as expected
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **Server Software**: Paper Spigot 1.17.1
          - **ProSkillAPI Version**: 1.1.7.3-ALPHA
          - **ProMCCore Version**: 1.0.3.1-ALPHA

        Then run `/plugins` on your server and paste that list for us.
      value: |
        - Server Software:
        - ProSkillAPI Version:
        - ProMCCore Version:
        - Plugins:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: latest.log
      description: |
        Assuming this bug causes an error, please stop your server, start it again, reproduce the error and then stop your server.
        Upload your latest.log either directly here or through a paste service like [pastebin](https://pastebin.com).
      value: |
        <details><summary>latest.log</summary>
        <p>
        
        ```log
        # paste log here...
        ```
        
        </p>
        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
