name: Dev Build

on:
  push:
    branches: [ dev ]
    paths: [ src/** ]

jobs:
  deploy:
    uses: magemonkeystudio/.github/.github/workflows/reusable-build.yml@main
    secrets: inherit
    with:
      is_dev: true
      update_javadocs: true
