name: Release Build

on:
  push:
    branches: [ main ]
    paths: [ src/** ]

jobs:
  deploy:
    uses: magemonkeystudio/.github/.github/workflows/reusable-build.yml@main
    secrets: inherit
    with:
      is_dev: false
